name: Build And Deploy To www.steveyuowo.com
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          ref: main
      - name: Install and Build
        run: yarn deploy
