name: Build And Deploy To www.steveyuowo.com
on:
  push:
    branches: [main]
  schedule:
    # see https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
    # run the schedule once per hour
    - cron: "55 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.18.1

      - name: Install package
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Upload assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "./public/*"
          target: "/usr/local/nginx/html"
